// Generated by AgentFoundry Agent Foundry — kit: claude-agent-sdk-ts
// Docs: https://docs.claude.com/en/api/agent-sdk/overview
//
// Run: npm install && npm run agent:dev
// Run with custom prompt: tsx agent.ts "your prompt here"
// Requires: ANTHROPIC_API_KEY in .env (or .env.local) at the project root.
//
// Every run is recorded to .codenow/runs/skill-gap-agent/ (JSONL) so you can replay
// it in the AgentFoundry IDE's Runs tab. The recorder fails silently — it will
// never break your agent.
//
// If a AgentFoundry Sidecar is running on this host (see ./sidecar.ts), its
// skills + guardrails are composed into the system prompt automatically.
// Without a sidecar the prefix is empty and the agent runs unchanged.

import * as fs from "node:fs";

// Load .env / .env.local into process.env so ANTHROPIC_API_KEY reaches the
// SDK without needing the dotenv package or `node --env-file=…`. AgentFoundry's
// runsFork spawns this script with an inherited process.env that doesn't
// see your interactive shell's exports, so the script must self-load.
for (const envFile of [".env", ".env.local"]) {
  try {
    for (const line of fs.readFileSync(envFile, "utf-8").split("\n")) {
      const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^"(.*)"$/, "$1");
    }
  } catch (_) { /* file optional */ }
}

import { query } from "@anthropic-ai/claude-agent-sdk";
import { record } from "./recorder";
import { loadSidecarSystemPrompt } from "./sidecar";

const DEFAULT_PROMPT = "List the files in this directory and tell me what kind of project this is.";
const SLUG = "skill-gap-agent";

async function main() {
  const prompt = process.argv[2] || DEFAULT_PROMPT;
  const sidecarPrompt = await loadSidecarSystemPrompt();
  const finalPrompt = sidecarPrompt
    ? `${sidecarPrompt}\n\n---\n\n${prompt}`
    : prompt;
  const stream = query({
    prompt: finalPrompt,
    options: {
      allowedTools: ["Bash", "Glob", "Read"],
    },
  });
  for await (const message of record(stream, { slug: SLUG, input: prompt, kit: "claude-agent-sdk-ts" })) {
    if ("result" in message) {
      console.log(message.result);
    }
  }
}

main().catch((err) => {
  console.error("agent error:", err);
  process.exit(1);
});
