// Generated by AgentFoundry Agent Foundry — DO NOT EDIT BY HAND.
// Records every agent run to .codenow/runs/{slug}/ as JSONL so the AgentFoundry IDE
// can replay it. Wraps any AsyncIterable<message> from the Claude Agent SDK
// (or any other source) and passes messages through unchanged.
//
// Each event is hash-chained (SHA-256, canonical-JSON) so the JSONL is
// tamper-evident. The chain head is also written to .codenow/runs/{slug}/heads.jsonl
// after run.end — that's the offline anchor target (push to S3 Object Lock /
// GCS Bucket Lock from your CI to lock the audit trail in place).
//
// Failure policy: this file MUST NEVER throw into your agent. Every IO call
// is wrapped in try/catch — if recording breaks, the agent keeps running.

import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";

const RUNS_DIR = ".codenow/runs";
const CAP_PER_SLUG = 100;
const CAP_TOTAL = 500;
const MAX_FIELD_BYTES = 100 * 1024; // truncate any single string field > 100KB
const HASH_DOMAIN = "codenow-v1";   // domain separator — must match recorder-hash.js

export type RecordOpts = {
  slug: string;
  input: string;
  kit?: string;
  agentVersion?: string;
  model?: string;
};

// Walks up from cwd looking for the AgentFoundry project root. Prefers
// .codenow/agent-studio (only present at the real project root, never inside
// a per-agent slug subfolder), falling back to .codenow.
// Pure best-effort — never throws.
function findProjectRoot(): string {
  let cur = process.cwd();
  for (let i = 0; i < 10; i++) {
    try {
      if (fs.existsSync(path.join(cur, ".codenow", "agent-studio"))) return cur;
    } catch {}
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  cur = process.cwd();
  for (let i = 0; i < 10; i++) {
    try {
      if (fs.existsSync(path.join(cur, ".codenow"))) return cur;
    } catch {}
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  return process.cwd();
}

function safeMkdir(p: string): void {
  try { fs.mkdirSync(p, { recursive: true }); } catch {}
}

// Truncates oversize string fields in-place during JSON serialization.
function truncReplacer(_k: string, v: unknown): unknown {
  if (typeof v === "string" && v.length > MAX_FIELD_BYTES) {
    return v.slice(0, MAX_FIELD_BYTES) + `…[truncated ${v.length - MAX_FIELD_BYTES} chars]`;
  }
  return v;
}

// Canonical JSON: keys sorted at every level, no whitespace. Skips _h and _p
// so hashes don't self-reference. Must match the JS reader and the Python
// recorder byte-for-byte.
function canonicalJSON(value: unknown): string {
  return JSON.stringify(canonicalize(value));
}
function canonicalize(value: unknown): unknown {
  if (value === null || typeof value !== "object") return truncReplacer("", value);
  if (Array.isArray(value)) return value.map(canonicalize);
  const obj = value as Record<string, unknown>;
  const out: Record<string, unknown> = {};
  const keys = Object.keys(obj).filter(k => k !== "_h" && k !== "_p").sort();
  for (const k of keys) out[k] = canonicalize(obj[k]);
  return out;
}

function hashEvent(event: unknown, prevHash: string | null): string {
  const h = crypto.createHash("sha256");
  h.update(HASH_DOMAIN);
  h.update("|");
  h.update(prevHash || "");
  h.update("|");
  h.update(canonicalJSON(event));
  return h.digest("hex");
}

// Writes one event to the JSONL, threading the hash chain. Returns the new
// head hash so the caller can keep it for the next event. Returns prevHash
// unchanged if writing failed — the chain stays consistent on disk.
function safeWriteEvent(fd: number | null, event: Record<string, unknown>, prevHash: string | null): string | null {
  const _h = hashEvent(event, prevHash);
  const stamped = { ...event, _p: prevHash, _h };
  if (fd == null) return _h; // no fd, but advance hash so callers stay consistent
  try {
    // Stamped event uses canonical JSON for stability — important so the IDE's
    // verifier can recompute byte-identical hashes from the file contents.
    const line = JSON.stringify(stamped, truncReplacer) + "\n";
    fs.writeSync(fd, line);
    return _h;
  } catch {
    return prevHash;
  }
}

// Side file: append the chain head after run.end so external anchoring can
// pick it up. One line per finished run: { runId, headHash, ts }.
function safeAppendHead(slugDir: string, runId: string, headHash: string | null): void {
  if (!headHash) return;
  try {
    const headsPath = path.join(slugDir, "heads.jsonl");
    fs.appendFileSync(headsPath, JSON.stringify({ runId, headHash, ts: Date.now() }) + "\n");
  } catch {}
}

// Async, fire-and-forget pruner. Keeps newest CAP_PER_SLUG per slug and
// CAP_TOTAL across all slugs by mtime. Errors are swallowed.
function pruneAsync(runsRoot: string): void {
  setTimeout(() => {
    try {
      const slugs = fs.readdirSync(runsRoot, { withFileTypes: true })
        .filter(d => d.isDirectory()).map(d => d.name);
      const allFiles: { slug: string; file: string; ts: number }[] = [];
      for (const slug of slugs) {
        const dir = path.join(runsRoot, slug);
        let files: string[] = [];
        try { files = fs.readdirSync(dir).filter(f => f.endsWith(".jsonl")); } catch { continue; }
        const stamped = files.map(f => {
          const stat = fs.statSync(path.join(dir, f));
          return { slug, file: path.join(dir, f), ts: stat.mtimeMs };
        }).sort((a, b) => b.ts - a.ts);
        for (let i = CAP_PER_SLUG; i < stamped.length; i++) {
          try { fs.unlinkSync(stamped[i].file); } catch {}
        }
        allFiles.push(...stamped.slice(0, CAP_PER_SLUG));
      }
      allFiles.sort((a, b) => b.ts - a.ts);
      for (let i = CAP_TOTAL; i < allFiles.length; i++) {
        try { fs.unlinkSync(allFiles[i].file); } catch {}
      }
    } catch {}
  }, 0).unref?.();
}

export async function* record<T>(
  stream: AsyncIterable<T>,
  opts: RecordOpts,
): AsyncGenerator<T, void, unknown> {
  const startTs = Date.now();
  const runId = (crypto.randomUUID?.() || String(startTs) + "-" + Math.random().toString(36).slice(2)).replace(/-/g, "").slice(0, 16);
  const projectRoot = findProjectRoot();
  const runsRoot = path.join(projectRoot, RUNS_DIR);
  const slugDir = path.join(runsRoot, opts.slug);
  safeMkdir(slugDir);
  pruneAsync(runsRoot);

  const filePath = path.join(slugDir, `${startTs}-${runId}.jsonl`);
  let fd: number | null = null;
  try { fd = fs.openSync(filePath, "a"); } catch { fd = null; }

  // Threaded hash — head moves forward with every event written. null = genesis.
  let head: string | null = null;

  head = safeWriteEvent(fd, {
    kind: "run.start",
    runId,
    slug: opts.slug,
    ts: startTs,
    input: opts.input,
    kit: opts.kit || null,
    model: opts.model || null,
    agentVersion: opts.agentVersion || null,
    source: "local",
  }, head);

  let lastResultMessage: unknown = null;
  let errored = false;
  try {
    for await (const message of stream) {
      head = safeWriteEvent(fd, { kind: "message", ts: Date.now(), message }, head);
      if (message && typeof message === "object" && "result" in (message as object)) {
        lastResultMessage = message;
      }
      yield message;
    }
  } catch (err) {
    errored = true;
    head = safeWriteEvent(fd, {
      kind: "run.error",
      ts: Date.now(),
      durationMs: Date.now() - startTs,
      error: { message: err instanceof Error ? err.message : String(err), stack: err instanceof Error ? err.stack : undefined },
    }, head);
    if (fd != null) try { fs.closeSync(fd); } catch {}
    safeAppendHead(slugDir, runId, head);
    throw err;
  }

  if (!errored) {
    head = safeWriteEvent(fd, {
      kind: "run.end",
      ts: Date.now(),
      durationMs: Date.now() - startTs,
      status: "success",
      resultMessage: lastResultMessage,
    }, head);
  }
  if (fd != null) try { fs.closeSync(fd); } catch {}
  safeAppendHead(slugDir, runId, head);
}
