// Generated by AgentFoundry Agent Foundry — safe to edit.
// Loads skills + guardrails from a locally-running AgentFoundry Sidecar at
// http://localhost:${process.env.CODENOW_SIDECAR_PORT || '8721'}/state and
// composes them into a system-prompt prefix.
//
// If the sidecar isn't reachable (not installed yet, network blip), this
// returns an empty string — your agent runs normally. By design: skills +
// guardrails are advisory in dev, enforced in production.

export type SidecarSkill = {
  id: number;
  agent_slug: string;
  title: string;
  body: string;
  source?: string;
  active?: boolean;
};
export type SidecarGuardrail = {
  id: number;
  agent_slug: string;
  policy: Record<string, unknown>;
  trustscore_floor?: number;
};

export async function loadSidecarSystemPrompt(): Promise<string> {
  const port = process.env.CODENOW_SIDECAR_PORT || "8721";
  const host = process.env.CODENOW_SIDECAR_HOST || "127.0.0.1";
  try {
    const ctl = new AbortController();
    const watchdog = setTimeout(() => ctl.abort(), 1500);
    const r = await fetch(`http://${host}:${port}/state`, { signal: ctl.signal });
    clearTimeout(watchdog);
    if (!r.ok) return "";
    const { skills = [], guardrails = [] } = (await r.json()) as {
      skills?: SidecarSkill[];
      guardrails?: SidecarGuardrail[];
    };
    if (skills.length === 0 && guardrails.length === 0) return "";
    const parts: string[] = [];
    if (skills.length) {
      parts.push("## Skills");
      for (const s of skills) {
        parts.push(`### ${s.title}\n${s.body}`);
      }
    }
    if (guardrails.length) {
      parts.push("## Guardrails");
      for (const g of guardrails) {
        const floor = typeof g.trustscore_floor === "number"
          ? `\nMinimum TrustScore: ${g.trustscore_floor}`
          : "";
        parts.push(`### ${g.agent_slug}\n${JSON.stringify(g.policy, null, 2)}${floor}`);
      }
    }
    return parts.join("\n\n");
  } catch {
    // Sidecar not running, network blip, or timed out — fail open.
    return "";
  }
}

// Best-effort: hand a recorded run to the sidecar so it forwards to AgentFoundry.
// Call from your agent's run-end hook. If the sidecar isn't running, the run
// still lives in .codenow/runs/<slug>/ on disk and gets picked up the next
// time AgentFoundry imports the project.
export async function postRunToSidecar(run: Record<string, unknown>): Promise<void> {
  const port = process.env.CODENOW_SIDECAR_PORT || "8721";
  const host = process.env.CODENOW_SIDECAR_HOST || "127.0.0.1";
  try {
    const ctl = new AbortController();
    const watchdog = setTimeout(() => ctl.abort(), 2000);
    await fetch(`http://${host}:${port}/runs`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(run),
      signal: ctl.signal,
    });
    clearTimeout(watchdog);
  } catch {
    /* fail open */
  }
}
